@startuml
hide footbox
skinparam style strictuml

participant "MoteurJeu" as Moteur
participant "laby : Labyrinth" as Laby
participant "case : Case" as C

Moteur -> Laby : genererPieces()
activate Laby

loop Pour chaque pièce à placer
    Laby -> Laby : coord = getCoordonneesAleatoires()
    Laby -> C : getType()
    C --> Laby : typeActuel
    
    alt typeActuel == LIBRE && coord != spawnJoueur
        note right of C : Critères 1, 3 et 4
        Laby -> C : setType('PIECE')
        Laby -> C : setTraversable(true)
    end
end

deactivate Laby
@enduml