@startuml

participant "joueur" as j
participant "labyrinth" as l
participant "piece" as p
-> j : deplacement()
activate j
j -> l : getNom()
activate l
l--> j : 'c'
deactivate l
j -> p : getPris()
activate p
p --> j : false
deactivate p
j -> j : augmenterScore()
j -> p : etrePris()
activate p
p --> j
deactivate p
<-- j

@enduml