@startuml
'https://plantuml.com/class-diagram
class DessinJeu{
- largeurDispo : int
- hauteurDispo : int
+ dessiner(image : BufferedImage)
}
class Jeu{
+ evoluer(c : Commande)
}
interface Case{
+ etreTraversable() : boolean
+ getNom() : char
}
class Mur implements Case{
+ etreTraversable() : boolean
+ getNom() : char
}
class Vide implements Case{
+ etreTraversable() : boolean
+ getNom() : char
}
class Piege implements Case {
+etreTraversable() : boolean
+getNom() : char
}
interface Personnage {
+ deplacement(dir: char, laby: Labyrinth)
+ getX() : int
+ getY() : int
}

class Labyrinth {
- tailleX : int
- tailleY : int
+ Labyrinth()

}

class Joueur implements Personnage {
- posX : int
- posY : int
- vie : int
+ deplacement(dir: char, laby: Labyrinth)
+ getX() : int
+ getY() : int
+ subirDegat(degat : int)
+ getVie() : int
+ etreMort() : boolean
}
class Piece implements Case{
+ etreTraversable() : boolean
+getNom() : char
}
DessinJeu -> "1" Jeu : -jeu
Jeu -> "1" Labyrinth : -laby
Jeu -> "1" Personnage : -pj
Labyrinth -> "*" Case : -grille
@enduml