@startuml

participant "dessinJeu" as dessin
participant "labyrinth" as laby
participant "piece" as p
-> dessin : dessiner()
activate dessin
loop laby.getTaille()
    dessin -> laby : getCase()
    activate laby
    laby --> dessin : piece
    deactivate laby
    dessin -> p : case.getPris()
    activate p
    p --> dessin : false
    deactivate p

    dessin -> dessin : .fillOval()
end
<-- dessin
deactivate laby

@enduml