@startuml

participant "Piège" as Jeu
participant "Joueur" as J
participant "Interface" as UI
Jeu -> J : subirDegats()
J -> J : mort = true
J -> UI : afficherGameOver()
UI -> J
Jeu -> J : deplacement()
J -> Jeu : action ignorée (car mort)

@enduml