@startuml
title Fonctionnalité 1 - Déplacement du joueur
participant "Jeu" as Jeu
participant "Joueur" as Joueur
participant "Labyrinth" as Labyrinth
-> Jeu : evoluer(Up)
activate "Jeu"
Jeu -> Joueur : deplacement('N', laby)
activate "Joueur"
Joueur -> Labyrinth : getTailleX() / getTailleY()
activate "Labyrinth"
Labyrinth --> Joueur : dimensions du labyrinthe
deactivate "Labyrinth"
"Joueur" -> "Labyrinth" : estTraversable(x, y)
activate "Labyrinth"
"Labyrinth" -> "Joueur" : true
deactivate "Labyrinth"
note left
    déplacement valide
end note
Joueur -> Joueur : met à jour posX / posY
"Joueur" --> "Jeu"
deactivate "Joueur"
<-- "Jeu"
deactivate "Jeu"

@enduml