@startuml
'https://plantuml.com/class-diagram
class Jeu{
}

interface Personnage {
+ deplacement(dir: char, laby: Labyrinth)
}

class Labyrinth {
+Labyrinth()
}

class Joueur implements Personnage {
- posX : int
- posY : int
+ deplacement(dir: char, laby: Labyrinth)
}

Jeu -> "1" Labyrinth : -laby
Jeu -> "1" Personnage : -pj
@enduml