@startuml
hide footbox
skinparam style strictuml

participant "Joueur" as J
participant "Labyrinth" as L
participant "Case" as C

-> J : deplacement(dir, laby)
note right
    comme y>0
end note
        J -> L : getCase(this.posX, this.posY-1)
        L -> J : case_cible
        J -> C : etreTraversable()
        C -> J : true
note left
    decrementation de y
end note
    

<- J : 

@enduml
